"""
Phase 5 — Sheet → Site pipeline
Fetches the published Google Sheet CSV (Sheet 2, verified listings only)
and regenerates data/deadlines.js for the static site.

Usage:
    python scripts/sheet_to_js.py                    # uses SHEET_CSV_URL env var
    python scripts/sheet_to_js.py --url <csv_url>    # explicit URL
    python scripts/sheet_to_js.py --local <file.csv> # test with local CSV

Expected Sheet 2 columns (order doesn't matter):
    id, employer, scheme_name, category, disciplines,
    opening_date, deadline, rolling_basis, locations,
    url, status, notes, verified

Rows where verified != TRUE are skipped.
"""

import argparse
import csv
import json
import os
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT    = Path(__file__).parent.parent
OUT_JS  = ROOT / "data" / "deadlines.js"
OUT_JSON = ROOT / "data" / "deadlines.json"

SHEET_CSV_URL = os.environ.get("SHEET_CSV_URL", "")


def fetch_csv(url):
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8")


def parse_bool(val):
    return str(val).strip().upper() in ("TRUE", "YES", "1", "T")


def parse_list(val, sep=";"):
    """Split a semicolon-separated string into a list, stripping whitespace."""
    if not val or not val.strip():
        return []
    return [v.strip() for v in val.split(sep) if v.strip()]


def parse_row(row):
    """Convert a Sheet row dict into our canonical listing schema."""
    disciplines = parse_list(row.get("disciplines", ""))
    locations   = parse_list(row.get("locations", ""))

    # Normalise status
    status = row.get("status", "open").strip().lower()
    if status not in ("open", "closed", "upcoming"):
        status = "open"

    return {
        "id":                row.get("id", "").strip(),
        "employer":          row.get("employer", "").strip(),
        "scheme_name":       row.get("scheme_name", "").strip(),
        "category":          row.get("category", "Graduate Scheme").strip(),
        "disciplines":       disciplines,
        "opening_date":      row.get("opening_date", "").strip() or None,
        "deadline":          row.get("deadline", "").strip() or None,
        "status":            status,
        "rolling_basis":     parse_bool(row.get("rolling_basis", "")),
        "early_closure_note":row.get("notes", "").strip() or None,
        "url":               row.get("url", "").strip(),
        "last_verified":     row.get("last_verified", "").strip() or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "last_scraped":      row.get("last_scraped", "").strip() or datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "locations":         locations,
    }


def load_csv_rows(content):
    reader = csv.DictReader(content.splitlines())
    listings = []
    skipped  = 0
    for row in reader:
        if not parse_bool(row.get("verified", "FALSE")):
            skipped += 1
            continue
        entry = parse_row(row)
        if not entry["id"] or not entry["employer"]:
            skipped += 1
            continue
        listings.append(entry)
    return listings, skipped


def write_outputs(listings):
    data = {"employers": listings}

    # deadlines.json — source of truth
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    # deadlines.js — what the site loads
    js_content = (
        "// Auto-generated from Google Sheet — do not edit manually.\n"
        "// Regenerated by scripts/sheet_to_js.py via GitHub Actions.\n"
        f"const DEADLINES_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    )
    with open(OUT_JS, "w", encoding="utf-8") as f:
        f.write(js_content)

    print(f"Written {len(listings)} listings to:")
    print(f"  {OUT_JSON}")
    print(f"  {OUT_JS}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--url",   help="Google Sheet published CSV URL")
    parser.add_argument("--local", help="Path to local CSV file (for testing)")
    args = parser.parse_args()

    if args.local:
        print(f"Loading local CSV: {args.local}")
        content = Path(args.local).read_text(encoding="utf-8")
    else:
        url = args.url or SHEET_CSV_URL
        if not url:
            print("ERROR: No CSV URL provided.")
            print("Set SHEET_CSV_URL env var or pass --url <url>")
            sys.exit(1)
        print(f"Fetching CSV from: {url}")
        content = fetch_csv(url)

    listings, skipped = load_csv_rows(content)
    print(f"Parsed {len(listings)} verified listings ({skipped} skipped)")

    if not listings:
        print("WARNING: 0 listings — not overwriting output files.")
        sys.exit(0)

    write_outputs(listings)


if __name__ == "__main__":
    main()
